[package]
name = "rdovetail"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.9", features = ["derive"] }
notify = "6.1.1"
sha2 = "0.10.8"
memmap2 = "0.9.4"
serde = {version = "1.0.210", features = ["derive"]}
bincode = "1.3.3"

